train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/mix_train_HR
      repeat: 5
      cache: bin
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: swinir
      args:
        img_size: 48
        patch_size: 1
        in_chans: 3
        embed_dim: 60
        depths: [6, 6, 6, 6]
        num_heads: [6, 6, 6, 6]
        window_size: 8
        mlp_ratio: 2.
        upscale: 1        # [重要] 設為 1，因為我們在程式碼中移除了上採樣
        img_range: 1.
        resi_connection: '1conv'
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [512, 512, 512, 512]

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
